language: elixir

sudo: required

services:
  - docker

elixir:
  - 1.8

otp_release:
  - 21.2

env:
  - NBX_TEST=true MIX_ENV=test DOCKER_COMPOSE_VERSION=1.22.0 REDIS_CLUSTER_IP=0.0.0.0

before_script:
  - docker-compose up -d
  - epmd -daemon
  - mix deps.get --only test

script:
  - mix coveralls.travis
  - mix dialyzer --plt
  - mix dialyzer --halt-exit-status
  - mix credo --strict
  - mix format --check-formatted

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
